apiVersion: v1
kind: Service
metadata:
  name: producto2-service
spec:
  selector:
    app: producto2 # Debe coincidir con el label del deployment
  type: NodePort # Exponemos el servicio en un puerto de tu VM
  ports:
    - protocol: TCP
      port: 80 # Puerto que el servicio expondr√° internamente
      targetPort: 8080 # Puerto del contenedor (debe coincidir con containerPort)